# Generated by Django 5.2.15 on 2026-06-14 15:54

import clientes.models
import clientes.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del contratante')),
                ('rut', models.CharField(max_length=20, unique=True, validators=[clientes.validators.validate_rut], verbose_name='RUT')),
                ('folio', models.CharField(blank=True, max_length=30, unique=True)),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Domicilio')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('occupation', models.CharField(blank=True, max_length=120, verbose_name='Ocupación')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('relationship', models.CharField(blank=True, max_length=120, verbose_name='Parentesco')),
                ('deceased_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del fallecido')),
                ('deceased_address', models.CharField(blank=True, max_length=250, verbose_name='Domicilio del fallecido')),
                ('deceased_rut', models.CharField(blank=True, max_length=20, verbose_name='RUT del fallecido')),
                ('birth_place', models.CharField(blank=True, max_length=150, verbose_name='Lugar de nacimiento')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('marital_status', models.CharField(blank=True, max_length=80, verbose_name='Estado civil')),
                ('education', models.CharField(blank=True, max_length=120, verbose_name='Estudios')),
                ('insurance', models.CharField(blank=True, max_length=120, verbose_name='Previsión')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('death_time', models.TimeField(blank=True, null=True, verbose_name='Hora de fallecimiento')),
                ('death_place', models.CharField(blank=True, max_length=250, verbose_name='Lugar de fallecimiento')),
                ('registration_place', models.CharField(blank=True, max_length=250, verbose_name='Lugar de inscripción')),
                ('parents', models.CharField(blank=True, max_length=300, verbose_name='Nombre de los padres')),
                ('urn_type', models.CharField(blank=True, max_length=150, verbose_name='Tipo de urna')),
                ('cemetery_transfer', models.CharField(blank=True, max_length=200, verbose_name='Traslado al cementerio')),
                ('wake_place', models.CharField(blank=True, max_length=250, verbose_name='Lugar de velación')),
                ('mass_date', models.DateField(blank=True, null=True, verbose_name='Fecha de misa')),
                ('mass_time', models.TimeField(blank=True, null=True, verbose_name='Hora de misa')),
                ('church', models.CharField(blank=True, max_length=200, verbose_name='Iglesia')),
                ('automobile', models.CharField(blank=True, max_length=150, verbose_name='Automóvil')),
                ('automobile_paid_by', models.CharField(blank=True, max_length=150, verbose_name='Automóvil pagado por')),
                ('minibus', models.CharField(blank=True, max_length=150, verbose_name='Microbús')),
                ('minibus_paid_by', models.CharField(blank=True, max_length=150, verbose_name='Microbús pagado por')),
                ('service_description', models.TextField(blank=True, verbose_name='Detalle del servicio')),
                ('service_net', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor neto del servicio')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, default=Decimal('19'), max_digits=5, verbose_name='IVA (%)')),
                ('seller_name', models.CharField(blank=True, max_length=160, verbose_name='Vendedor')),
                ('contract_place', models.CharField(blank=True, default='Limache', max_length=100, verbose_name='Lugar del contrato')),
                ('contract_date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Fecha del contrato')),
                ('documents_recipient', models.CharField(blank=True, max_length=200, verbose_name='Receptor de documentos')),
                ('documents_relationship', models.CharField(blank=True, max_length=100, verbose_name='Parentesco del receptor')),
                ('documents_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('documents_detail', models.TextField(blank=True, verbose_name='Documentos entregados')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('document_folder', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('contrato', 'Contrato físico'), ('certificado', 'Certificado'), ('comprobante', 'Comprobante'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo')),
                ('file', models.FileField(upload_to=clientes.models.client_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='Archivo')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clientes.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha del abono')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Valor')),
                ('receipt_number', models.CharField(blank=True, max_length=80, verbose_name='N° de recibo')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clientes.client')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['payment_date', 'created_at'],
            },
        ),
    ]
